language: node_js
node_js:
  - 0.10
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "grunt test $TEST_SUITE"
env:
  global:
    - COVERALLS_REPO_TOKEN=m3Z9p5t4SQLKw22IE9mkdr1iFSVpeJPoV
  matrix:
    - TEST_SUITE=--skip=test/integration/**/*_nd*
    - TEST_SUITE=--file=test/integration/**/*_nd*
  allow_failures:
    - TEST_SUITE=--file=test/integration/**/*_nd*
