language: node_js
node_js:
  - 0.10
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "grunt test $TEST_SUITE"
env:
  TEST_SUITE: --skip=test/integration/**/nd_*
  TEST_SUITE: --file=test/integration/**/nd_*
  global:
    - COVERALLS_REPO_TOKEN=m3Z9p5t4SQLKw22IE9mkdr1iFSVpeJPoV
